const ACTION_TYPES = {
    TOAST_ALERT: {
        OPEN_TOAST: 'OPEN_TOAST',
        CLEAR_TOAST: 'CLEAR_TOAST'
    },
    CHATBOT: {
        SEND_MESSAGE_TO_LIST: 'CHATBOT_SEND_MESSAGE_TO_LIST',
        FETCH_BOT_ANSWER: {
            SUCCESS: 'FETCH_BOT_ANSWER_SUCCESS',
            FAILURE: 'FETCH_BOT_ANSWER_FAILURE'
        },
        CLEAN_ALL_MESSAGES: 'CHATBOT_CLEAN_ALL_MESSAGES'
    },
    PAGE_TITLE_CHANGED: 'PAGE_TITLE_CHANGED',
    LOADING: 'LOADING_PROGRESS',
};

export {ACTION_TYPES}